apiVersion: v1
kind: Secret
metadata:
  name: app-api-secrets
  namespace: app
type: Opaque
stringData:
  ConnectionStrings__Default: Host=10.10.10.10;Port=5432;Database=app_db;Username=app_user;Password=CHANGE_ME
