apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: infra
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "CHANGE_ME",
      "TunnelSecret": "CHANGE_ME",
      "TunnelID": "CHANGE_ME",
      "TunnelName": "app-cluster"
    }
