services:
  ${APP_NAME}-blue:
    image: ${APP_IMAGE}
    container_name: ${APP_NAME}-blue
    restart: unless-stopped
    env_file:
      - ${APP_ENV_ROOT}/common.env
      - ${APP_ENV_ROOT}/blue.env
    stop_signal: SIGTERM
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${APP_INTERNAL_PORT}/.well-known/live || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - ${APP_NETWORK_NAME}

  ${APP_NAME}-green:
    image: ${APP_IMAGE}
    container_name: ${APP_NAME}-green
    restart: unless-stopped
    env_file:
      - ${APP_ENV_ROOT}/common.env
      - ${APP_ENV_ROOT}/green.env
    stop_signal: SIGTERM
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${APP_INTERNAL_PORT}/.well-known/live || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - ${APP_NETWORK_NAME}

networks:
  ${APP_NETWORK_NAME}:
    external: true
