---
- name: Install Nginx
  apt:
    name:         nginx
    state:        present
    update_cache: true

- name: Remove default Nginx site
  file:
    path:  /etc/nginx/sites-enabled/default
    state: absent

- name: Render Nginx configs for native app instances
  include_tasks: nginx_instance.yml
  loop: "{{ native_apps }}"
  loop_control:
    loop_var: current_app
    label: "{{ current_app.name }}"

- name: Validate nginx config
  command: nginx -t
  changed_when: false

- name: Ensure nginx is enabled and started
  service:
    name:    nginx
    enabled: true
    state:   started
