---
- name: Ensure applications root exists
  file:
    path: "{{ apps_root }}"
    state: directory
    owner: deploy
    group: deploy
    mode: '0755'

- name: Provision application runtimes
  include_tasks: app.yml
  loop: "{{ applications }}"
  loop_control:
    loop_var: app
